### ISSUE TITLE
Window content does not resize along with window resizing

### ISSUE THREAD

**Issue by FMMadsen** [Telpe/AppManager#15]
The outer window can be resized, but the content inside does not scale or move.
Suggest that either the outer window cannot be resized or the content should scale along with the window frame.

![Skærmbillede 2023-10-25 23 16 12](https://github.com/Telpe/AppManager/assets/32270729/f9bec9c0-efcb-41ae-a761-828d40a2458e)

**Comment by Telpe** [comment]
the window scaling is a coming feature #7 
content is not supposed to scale with window size.
