### ISSUE TITLE
Closing an app, does not inform about the result of the action

### ISSUE THREAD

**Issue by FMMadsen** [Telpe/AppManager#17]
As a user of the app I am in doubt after closing an app, if it happened or not.
No notification are shown or status message.

Suggest a log panel to the right side, showing activities completed.

**Comment by Telpe** [comment]
the numbers show how many instances is running of that application. 
the number in app row, should go to zero after close.
atm force exit apps is always on.
a color is considered to show if 0 or more are running
Feedback to user #9

**Comment by Telpe** [comment]
@FMMadsen could you see if the numbers are changing for apps on your pc?

**Comment by FMMadsen** [comment]
Yes, the number goes from 6 -> 0 when closing for example Discord.
I didn't notice at first.

Suggest to place a notification popup when some effect has happened. Or increase the focus on the numbering to make it easily recognizable what it is.

**Comment by Telpe** [comment]
Great suggestions.
I will add them to issue #9
