### ISSUE TITLE
"Add App" does not seem to be working

### ISSUE THREAD

**Issue by FMMadsen** [Telpe/AppManager#18]
Steps to reproduce:

1. Remove all checkmarks
2. checkmark "Discord"
3. Click "Add App"
4. Nothing happens

Expected behavior
4. Discord app would open

**Comment by Telpe** [comment]
add app is not open app. (open app #4 )
add app to the list so it can be managed.
the button should add a new empty row for user to write the name of the app to add.

atm, to remove app from list, simply delete it's name. 
the row will stay untill AppManager closes. see #13 .
