### ISSUE TITLE
3 checkboxes in a row. What are they for?

### ISSUE THREAD

**Issue by FMMadsen** [Telpe/AppManager#19]
3 checkboxes are shown for each application.
It is not described or intuitive to understand - why are they there?

![Skærmbillede 2023-10-25 23 24 23 marking](https://github.com/Telpe/AppManager/assets/32270729/8f798c0d-43da-4174-bc72-5b1fc55809fc)

**Comment by Telpe** [comment]
see #5 
this is not a released product.
it is working, but not released.
many things will not be explained by documentation nor in-app.
Features may be integrated in only one part of the app, and not yet functioning.
Read the issues and perhaps it make sense.

As release approach, features will mostly be fully integrated through branches, before applied to main branch.
but for now, everything is features, så they will not have their own branch.
