### ISSUE TITLE
List of apps are not updated for current environment

### ISSUE THREAD

**Issue by FMMadsen** [Telpe/AppManager#20]
It seems as the list of apps in the App Manager are not showing the actual relevant list for the current environment it is running in.

![Skærmbillede 2023-10-25 23 24 23 marking2](https://github.com/Telpe/AppManager/assets/32270729/276f0312-1204-4581-99a7-a5dbab18cc26)

**Comment by Telpe** [comment]
the AppManager is not a replacement for windows TaskManager.
ApManager will not show all apps and background apps running on user pc.
It will not scan the computer for apps.

AppManager will only check the apps on the user's list.

Atm. AppManager have a default starter list, as an example.
see #13
